import blurs from "./blur-data.json";
import type { Photo } from "./content";

/**
 * Attach the inline placeholder for a photograph, so its frame shows a
 * blurred wash of the real picture from the first paint instead of an empty
 * band while the full image arrives.
 *
 * The placeholders live in blur-data.json, generated by
 * `npm run images:blur` from 16px, quality 1 versions of each photograph.
 * They have to be inline data URLs: next/image wraps the placeholder in an
 * SVG filter, and an SVG used as a background cannot load an external file,
 * so a plain Cloudinary URL there would render nothing.
 *
 * Call this in a server component and pass the result down. Importing the
 * JSON from a client component would ship every placeholder in the bundle.
 */
const BLURS = blurs as Record<string, string>;

export function withBlur<T extends Photo>(photo: T): T {
  const blur = BLURS[photo.src];
  return blur ? { ...photo, blur } : photo;
}
